-- 2026-06-17 — Bengaluru locality -> RMP 2031 Planning District lookup
-- Source: RMP 2031 (Draft) Volume-4 Planning District Report + Index Map (BDA, Nov 2017).
-- PD numbering/names are VERBATIM from the live evidence_facts PDR-demographics fact
-- (authoritative). This table lets the parcel-context resolver map a geocoded
-- address locality/ward/village to its Planning District deterministically, without
-- the (unavailable) PD boundary polygons. Reference data: universal-read RLS, seed-only.
-- Generated deterministically from validated source JSON — do not hand-edit rows.

CREATE TABLE IF NOT EXISTS regulatory_data.district_localities (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  city          text NOT NULL DEFAULT 'Bengaluru',
  pd_number     int  NOT NULL,
  pd_code       text NOT NULL,
  pd_name       text NOT NULL,
  within_bbmp   boolean NOT NULL DEFAULT false,
  locality      text NOT NULL,
  locality_norm text NOT NULL,
  kind          text NOT NULL DEFAULT 'locality',
  confidence    text NOT NULL DEFAULT 'high',
  source        text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_district_localities_norm ON regulatory_data.district_localities (locality_norm);
CREATE UNIQUE INDEX IF NOT EXISTS uq_district_localities ON regulatory_data.district_localities (city, locality_norm, pd_number);

ALTER TABLE regulatory_data.district_localities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS district_localities_select_all ON regulatory_data.district_localities;
CREATE POLICY district_localities_select_all ON regulatory_data.district_localities FOR SELECT USING (true);

-- Idempotent re-seed: clear prior rows from these sources, then insert.
DELETE FROM regulatory_data.district_localities
  WHERE source IN ('RMP 2031 Vol-4 PDR — PD name','RMP 2031 Index Map (BDA, Nov 2017)');

INSERT INTO regulatory_data.district_localities
  (city, pd_number, pd_code, pd_name, within_bbmp, locality, locality_norm, kind, confidence, source) VALUES
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Bharathi Nagar', 'bharathinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Central Business District', 'centralbusinessdistrict', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Chikpete', 'chikpete', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Cottonpet', 'cottonpet', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Dayananda Nagar', 'dayanandanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Dharmarayaswamy Temple Ward', 'dharmarayaswamytempleward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Gandhi Nagar', 'gandhinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Gayathri Nagar', 'gayathrinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Jayamahal', 'jayamahal', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'K.R.Market', 'krmarket', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Okalipuram', 'okalipuram', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Prakash Nagar', 'prakashnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Pulikeshi Nagar', 'pulikeshinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Sampangiram Nagar', 'sampangiramnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Shanthala Nagar', 'shanthalanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Shivaji Nagar', 'shivajinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Subhash Nagar', 'subhashnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Sudam Nagar', 'sudamnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Ulsoor', 'ulsoor', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 1, 'PD-01', 'Central Business District', true, 'Vasanth Nagar', 'vasanthnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Benniganahalli', 'benniganahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'C.V.Raman Nagar', 'cvramannagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Dommalur', 'dommalur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Hosathippasandra', 'hosathippasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Hoysala Nagar', 'hoysalanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Indiranagar', 'indiranagar', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Jeevanbhima Nagar', 'jeevanbhimanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Jogupalya', 'jogupalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Kagadasapura', 'kagadasapura', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Maruthi Seva Nagar', 'maruthisevanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Sarvagna Nagar', 'sarvagnanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 2, 'PD-02', 'Indiranagar - Kagadasapura', true, 'Vignana Nagar', 'vignananagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Adugodi', 'adugodi', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Agaram', 'agaram', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Austin Town', 'austintown', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Ejipura', 'ejipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'HSR Layout', 'hsrlayout', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Jakkasandra', 'jakkasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Koramangala', 'koramangala', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Neelasandra', 'neelasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Shanthi Nagar', 'shanthinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 3, 'PD-03', 'Austin Town-Koramangala-HSR Layout', true, 'Vannarpet', 'vannarpet', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Basavangudi', 'basavangudi', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Byrasandra', 'byrasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Hombegowda Nagar', 'hombegowdanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Jayanagar', 'jayanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Jayanagara', 'jayanagara', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Lakkasandra', 'lakkasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Siddapura', 'siddapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Sudduguntepalya', 'sudduguntepalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Sunkenahalli', 'sunkenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Visvesvarapuram', 'visvesvarapuram', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 4, 'PD-04', 'Jayanagara', true, 'Yadiyuru', 'yadiyuru', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Agrahara Dasarahalli', 'agraharadasarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Attiguppe', 'attiguppe', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Azad Nagar', 'azadnagar', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Bapuji Nagar', 'bapujinagar', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Basaveshwara Nagar', 'basaveshwaranagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Binnipet', 'binnipet', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Chalavadipalya', 'chalavadipalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Chamrajpet', 'chamrajpet', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Dr.Rajkumar Ward', 'drrajkumarward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Gali Anjaneya Swamy Temple Ward', 'galianjaneyaswamytempleward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Govindraja Nagar', 'govindrajanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Hampi Nagar', 'hampinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Hosahalli', 'hosahalli', 'village', 'low', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Jagareevanram Nagar', 'jagareevanramnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Kempapura Agrahara', 'kempapuraagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Marenahalli', 'marenahalli', 'village', 'low', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Maruthi Mandira Ward', 'maruthimandiraward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Padarayanapura', 'padarayanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Rajaji Nagar', 'rajajinagar', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Rayapuram', 'rayapuram', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Shiva Nagar', 'shivanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Sri Rammandira', 'srirammandira', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 5, 'PD-05', 'Rajaji Nagar-Bapuji Nagar-Azad Nagar', true, 'Vijay Nagar', 'vijaynagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Aramane Nagar', 'aramanenagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Dattathreya Temple Ward', 'dattathreyatempleward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'H.M.T Ward', 'hmtward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Jalahalli', 'jalahalli', 'village', 'low', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'J.P.Park', 'jppark', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Kadumalleshwara', 'kadumalleshwara', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Lakshmidevi Nagar', 'lakshmidevinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Mahalakshmipuram', 'mahalakshmipuram', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Malleshwaram', 'malleshwaram', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Malleswaram', 'malleswaram', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Marappana Palya', 'marappanapalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Mathikere', 'mathikere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Nagapura', 'nagapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Nandini Layout', 'nandinilayout', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Rajamahal', 'rajamahal', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Subramanya Nagar', 'subramanyanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Yeshwanthpur', 'yeshwanthpur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 6, 'PD-06', 'Yeshwantpur - Malleswaram', true, 'Yeshwantpur', 'yeshwantpur', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Byatarayanapura', 'byatarayanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Doddabommasandra', 'doddabommasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Ganga Nagar', 'ganganagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Gangenahalli', 'gangenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'GKVK', 'gkvk', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Hebbal', 'hebbal', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Jayachamarajendra Nagar', 'jayachamarajendranagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Kodigehalli', 'kodigehalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Manorayanapalya', 'manorayanapalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Radhakrishna Temple Ward', 'radhakrishnatempleward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'RT Nagar', 'rtnagar', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Sanjay Nagar', 'sanjaynagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Vidyaranyapura', 'vidyaranyapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 7, 'PD-07', 'RT Nagar - Hebbal-GKVK', true, 'Vishwanathnagenahalli', 'vishwanathnagenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Devarajeevanahalli', 'devarajeevanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'HBR Layout', 'hbrlayout', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Kacharakanahalli', 'kacharakanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Kadugondanahalli', 'kadugondanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Kammanahalli', 'kammanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Kavalbyrasandra', 'kavalbyrasandra', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Kushal Nagar', 'kushalnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Lingarajapura', 'lingarajapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Muneshwara Nagar', 'muneshwaranagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Nagavara', 'nagavara', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Nagawara', 'nagawara', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Ramaswamy Palya', 'ramaswamypalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Richards Town', 'richardstown', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Sagayapuram', 'sagayapuram', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'S.K.Garden', 'skgarden', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 8, 'PD-08', 'Thanisandra-Nagawara-Richards Town', true, 'Thanisandra', 'thanisandra', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 9, 'PD-09', 'Banaswadi - Horamavu', true, 'Banasawadi', 'banasawadi', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 9, 'PD-09', 'Banaswadi - Horamavu', true, 'Banaswadi', 'banaswadi', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 9, 'PD-09', 'Banaswadi - Horamavu', true, 'Horamavu', 'horamavu', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 9, 'PD-09', 'Banaswadi - Horamavu', true, 'Ramamurthy Nagar', 'ramamurthynagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 10, 'PD-10', 'KR Puram - Hoodi', true, 'A.Narayanapura', 'anarayanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 10, 'PD-10', 'KR Puram - Hoodi', true, 'Basavanapura', 'basavanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 10, 'PD-10', 'KR Puram - Hoodi', true, 'Devasandra', 'devasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 10, 'PD-10', 'KR Puram - Hoodi', true, 'Hoodi', 'hoodi', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 10, 'PD-10', 'KR Puram - Hoodi', true, 'KR Puram', 'krpuram', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 10, 'PD-10', 'KR Puram - Hoodi', true, 'Vijinapura', 'vijinapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 11, 'PD-11', 'Dodda Nekkundi - Whitefield', true, 'Dodda Nekkundi', 'doddanekkundi', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 11, 'PD-11', 'Dodda Nekkundi - Whitefield', true, 'Garudacharpalya', 'garudacharpalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 11, 'PD-11', 'Dodda Nekkundi - Whitefield', true, 'Hagadooru', 'hagadooru', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 11, 'PD-11', 'Dodda Nekkundi - Whitefield', true, 'Kadugudi', 'kadugudi', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 11, 'PD-11', 'Dodda Nekkundi - Whitefield', true, 'Whitefield', 'whitefield', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 12, 'PD-12', 'Bellandur - Haralur', true, 'Bellandur', 'bellandur', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 12, 'PD-12', 'Bellandur - Haralur', true, 'HAL Airport', 'halairport', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 12, 'PD-12', 'Bellandur - Haralur', true, 'Haralur', 'haralur', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 12, 'PD-12', 'Bellandur - Haralur', true, 'Konena Agrahara', 'konenaagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 12, 'PD-12', 'Bellandur - Haralur', true, 'Marathalli', 'marathalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 13, 'PD-13', 'Parappana Agrahara - Hulimavu', true, 'Arakere', 'arakere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 13, 'PD-13', 'Parappana Agrahara - Hulimavu', true, 'Begur', 'begur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 13, 'PD-13', 'Parappana Agrahara - Hulimavu', true, 'Hongasandra', 'hongasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 13, 'PD-13', 'Parappana Agrahara - Hulimavu', true, 'Hulimavu', 'hulimavu', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 13, 'PD-13', 'Parappana Agrahara - Hulimavu', true, 'Mangammanapalya', 'mangammanapalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 13, 'PD-13', 'Parappana Agrahara - Hulimavu', true, 'Parappana Agrahara', 'parappanaagrahara', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 13, 'PD-13', 'Parappana Agrahara - Hulimavu', true, 'Singasandra', 'singasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Banashankari', 'banashankari', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Banashankari Temple Ward', 'banashankaritempleward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Bilekahalli', 'bilekahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Bommanahalli', 'bommanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'BTM Layout', 'btmlayout', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Gurappanapalya', 'gurappanapalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Jaraganahalli', 'jaraganahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Jayanagar East', 'jayanagareast', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'J.P.Nagar', 'jpnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Karisandra', 'karisandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Kumaraswamy Layout', 'kumaraswamylayout', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Madivala  JP Nagar', 'madivalajpnagar', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Madiwala', 'madiwala', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Pattabhiram Nagar', 'pattabhiramnagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Puttenahalli', 'puttenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Sarakki', 'sarakki', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Shakambari Nagar', 'shakambarinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 14, 'PD-14', 'Banashankari - BTM - Madivala (JP Nagar)', true, 'Yelachenahalli', 'yelachenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Chikkalasandra', 'chikkalasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Ganeshmandira Ward', 'ganeshmandiraward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Giri Nagar', 'girinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Hanumantha Nagar', 'hanumanthanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Hosakerehalli', 'hosakerehalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Kathriguppe', 'kathriguppe', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Katriguppe', 'katriguppe', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Padmanabha Nagar', 'padmanabhanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Sri Nagar', 'srinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Vasanthapura', 'vasanthapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 15, 'PD-15', 'Kathriguppe', true, 'Vidyapeetha Ward', 'vidyapeethaward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Anjanapur', 'anjanapur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Anjanapura', 'anjanapura', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Gottigere', 'gottigere', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Hemmigepura', 'hemmigepura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Konanakunte', 'konanakunte', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Mallasandra', 'mallasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Uttarahalli', 'uttarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Uttarahalli Manavarthi Kavalu', 'uttarahallimanavarthikavalu', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 16, 'PD-16', 'Gottigere - Anjanapura', true, 'Vasanthapura', 'vasanthapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 17, 'PD-17', 'Nayanadahalli', true, 'Deepanjali Nagar', 'deepanjalinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 17, 'PD-17', 'Nayanadahalli', true, 'Jnanabharathi Ward', 'jnanabharathiward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 17, 'PD-17', 'Nayanadahalli', true, 'Nagarabhavi', 'nagarabhavi', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 17, 'PD-17', 'Nayanadahalli', true, 'Nayanadahalli', 'nayanadahalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 17, 'PD-17', 'Nayanadahalli', true, 'Nayandanahalli', 'nayandanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 17, 'PD-17', 'Nayanadahalli', true, 'Rajarajeshwari Nagar', 'rajarajeshwarinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Kamakshipalya', 'kamakshipalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Kaveripura', 'kaveripura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Kottigepalya', 'kottigepalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Laggere', 'laggere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Moodalapalya', 'moodalapalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Nagarbhavi', 'nagarbhavi', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Peenya', 'peenya', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Peenya Industrial Area', 'peenyaindustrialarea', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Rajagopala Nagar', 'rajagopalanagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Shakthiganapathi Nagar', 'shakthiganapathinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Shankaramata', 'shankaramata', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 18, 'PD-18', 'Peenya - Nagarbhavi', true, 'Vrushabhavathi Nagar', 'vrushabhavathinagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'Bagalagunte', 'bagalagunte', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'Chokkasandra', 'chokkasandra', 'locality', 'low', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'Jalahalli', 'jalahalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'Jarakabandekaval', 'jarakabandekaval', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'Kuvempu Nagar', 'kuvempunagar', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'Mallasandra', 'mallasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'Shettyhalli', 'shettyhalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 19, 'PD-19', 'Jalahalli - Jarakabandekaval', true, 'T-Dasarahalli', 'tdasarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 20, 'PD-20', 'Yelahanka', true, 'Attur', 'attur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 20, 'PD-20', 'Yelahanka', true, 'Chowdeshwari Ward', 'chowdeshwariward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 20, 'PD-20', 'Yelahanka', true, 'Jakkur', 'jakkur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 20, 'PD-20', 'Yelahanka', true, 'Kempegowda Ward', 'kempegowdaward', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 20, 'PD-20', 'Yelahanka', true, 'Yelahanka', 'yelahanka', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 20, 'PD-20', 'Yelahanka', true, 'Yelahanka Satellite Town', 'yelahankasatellitetown', 'ward', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Bagaluru', 'bagaluru', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Bommasandra', 'bommasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Chagalatti', 'chagalatti', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Chikkagubbi', 'chikkagubbi', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Dasanayakanahalli', 'dasanayakanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Doddenahalli', 'doddenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Kadosonappanahalli', 'kadosonappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Kannur', 'kannur', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Marenahalli', 'marenahalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Mittaganahalli', 'mittaganahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Nadagowdagollahalli', 'nadagowdagollahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 21, 'PD-21', 'Marenahalli - Kannur', false, 'Yarappanahalli', 'yarappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Adur', 'adur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Anagalapura', 'anagalapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Bidarahalli', 'bidarahalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Byappanahalli', 'byappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Doddagubbi (Srigubbi)', 'doddagubbisrigubbi', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Halehalli', 'halehalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Hirandahalli', 'hirandahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Huvina Ane', 'huvinaane', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Kada Agrahara', 'kadaagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Kithiganur', 'kithiganur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Maragondanahalli', 'maragondanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Ramapura', 'ramapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 22, 'PD-22', 'Bidarahalli', false, 'Vaddarahalli', 'vaddarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Avalahalli', 'avalahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Bandapura', 'bandapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Belathur', 'belathur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Bidarena Agrahara', 'bidarenaagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Cheemasandra', 'cheemasandra', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Chikkabanahalli', 'chikkabanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Doddabanahalli', 'doddabanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Dommasandra', 'dommasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Goravikere', 'goravikere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Kajisonnenahalli', 'kajisonnenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Kannamangala', 'kannamangala', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Katamanallur', 'katamanallur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Konadasapura', 'konadasapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Kumbena Agrahara', 'kumbenaagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Kurudu Sonnenahalli', 'kurudusonnenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Nimbekayapura', 'nimbekayapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Shigehalli', 'shigehalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 23, 'PD-23', 'Cheemasandra Special Development Zone', false, 'Veerenahalli', 'veerenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 24, 'PD-24', 'Varthur - Gunjur', true, 'Gunjur', 'gunjur', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 24, 'PD-24', 'Varthur - Gunjur', true, 'Valepura', 'valepura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 24, 'PD-24', 'Varthur - Gunjur', true, 'Varthur', 'varthur', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Chikkakanneli', 'chikkakanneli', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Chikkanayakanahalli', 'chikkanayakanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Hadosiddapura', 'hadosiddapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Halanayakanahalli', 'halanayakanahalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Kachamaranahalli', 'kachamaranahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Kodathi', 'kodathi', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Mallur', 'mallur', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 25, 'PD-25', 'Halanayakanahalli - Kodathi Special Development Zone', false, 'Sulakunte', 'sulakunte', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Chikkanekkundi', 'chikkanekkundi', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Chikkavaderapura', 'chikkavaderapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Dommasandra', 'dommasandra', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Halasahalli Thippasandra', 'halasahallithippasandra', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Heggondahalli', 'heggondahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Nekkundi Dommasandra', 'nekkundidommasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Ramanayikanahalli', 'ramanayikanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 26, 'PD-26', 'Dommasandra Special Development Zone', false, 'Thigalachavadadenahalli', 'thigalachavadadenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Avalahalli', 'avalahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Chikkanagamangala', 'chikkanagamangala', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Chokkasandra', 'chokkasandra', 'locality', 'low', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Choodasandra', 'choodasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Ghottamaranahalli', 'ghottamaranahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Ghuttihalli', 'ghuttihalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Gollahalli', 'gollahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Gulamangala', 'gulamangala', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Harohalli', 'harohalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Hebbagodi', 'hebbagodi', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Hosahalli', 'hosahalli', 'village', 'low', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Huskuru', 'huskuru', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Kaggalipura', 'kaggalipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Kommasandra', 'kommasandra', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Madivala', 'madivala', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Rayasandra', 'rayasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Shingena Agrahara', 'shingenaagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Shrirampura', 'shrirampura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Singasandra', 'singasandra', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Thirupalya', 'thirupalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 27, 'PD-27', 'Singasandra-Hebbagodi-Kommasandra', false, 'Veerasandra', 'veerasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Bettadasanapura', 'bettadasanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Dodda Nagamangala', 'doddanagamangala', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Doddathoguru', 'doddathoguru', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Electronic City', 'electroniccity', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Hommadevanahalli', 'hommadevanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Konappana Agrahara', 'konappanaagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Mylasandra', 'mylasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 28, 'PD-28', 'Electronic City - Doddathoguru', false, 'Vittasandra', 'vittasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 29, 'PD-29', 'Hulimangala', false, 'Hulimangala', 'hulimangala', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 29, 'PD-29', 'Hulimangala', false, 'Maragondahalli', 'maragondahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 29, 'PD-29', 'Hulimangala', false, 'Nanjapura', 'nanjapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 29, 'PD-29', 'Hulimangala', false, 'Sarvamanya Bangipura', 'sarvamanyabangipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 29, 'PD-29', 'Hulimangala', false, 'Vabasandra', 'vabasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Badamanavarthikaval', 'badamanavarthikaval', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Bannerugatta', 'bannerugatta', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Bannerugattada Kavalu', 'bannerugattadakavalu', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Bannerughatta', 'bannerughatta', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Begihalli', 'begihalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Bhoothanahalli', 'bhoothanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Bhujengadasana Amanikere', 'bhujengadasanaamanikere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Bhyrappanahalli', 'bhyrappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Bilvaaradahalli', 'bilvaaradahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Gollahalli', 'gollahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Halesampigehalli', 'halesampigehalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Hullahalli', 'hullahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Hullakasavanahalli', 'hullakasavanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Kallakere', 'kallakere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Kannaikana Agrahara', 'kannaikanaagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Lakshmipura', 'lakshmipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Mallasandra', 'mallasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Mantapa', 'mantapa', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Nallasandra', 'nallasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Obichudahalli', 'obichudahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Ramasandra', 'ramasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Sakalavara', 'sakalavara', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 30, 'PD-30', 'Bannerughatta', false, 'Vaderahalli', 'vaderahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 31, 'PD-31', 'Agara', false, 'Agara', 'agara', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 31, 'PD-31', 'Agara', false, 'Badamanavarthe Kaval', 'badamanavarthekaval', 'village', 'low', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 32, 'PD-32', 'Ullalu - Kengeri', true, 'Hemmigepura', 'hemmigepura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 32, 'PD-32', 'Ullalu - Kengeri', true, 'Kengeri', 'kengeri', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 32, 'PD-32', 'Ullalu - Kengeri', true, 'Ullalu', 'ullalu', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 33, 'PD-33', 'Herohalli', true, 'Chikkabidarakallu', 'chikkabidarakallu', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 33, 'PD-33', 'Herohalli', true, 'Dodda Bidarkallu', 'doddabidarkallu', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 33, 'PD-33', 'Herohalli', true, 'Hegganahalli', 'hegganahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 33, 'PD-33', 'Herohalli', true, 'Herohalli', 'herohalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 33, 'PD-33', 'Herohalli', true, 'Srikantapura K G', 'srikantapurakg', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 33, 'PD-33', 'Herohalli', true, 'Thirumalapura', 'thirumalapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Byalakere', 'byalakere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Chikkabanavara', 'chikkabanavara', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Chikkabanwara', 'chikkabanwara', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Ganigerahalli', 'ganigerahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Guladahalli', 'guladahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Guniagrahara', 'guniagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Kalathammanahalli', 'kalathammanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Kasaghattapura', 'kasaghattapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Kempanahalli', 'kempanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Kempapura', 'kempapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Kumbarahalli', 'kumbarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Lakshmipura', 'lakshmipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Medi Agrahara', 'mediagrahara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Shamarajapura', 'shamarajapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Soladevanahalli', 'soladevanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Somashettahalli', 'somashettahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Vaderahalli', 'vaderahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 34, 'PD-34', 'Chikkabanwara', false, 'Veerasagara', 'veerasagara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Bettahalasuru', 'bettahalasuru', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Byappanahalli', 'byappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Gantiganahalli', 'gantiganahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Hunasamaranahalli', 'hunasamaranahalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Lakshmisagara', 'lakshmisagara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Muddanahalli', 'muddanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Nagadasanahalli', 'nagadasanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Nellukunte', 'nellukunte', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Sathanuru', 'sathanuru', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Sonnappanahalli', 'sonnappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Sugatta', 'sugatta', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 35, 'PD-35', 'Bettahalasuru-Hunasamaranahalli Special Development Zone', false, 'Thimmasandra', 'thimmasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Chellagatta', 'chellagatta', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Devageri', 'devageri', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Doddabele', 'doddabele', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Gudimavu', 'gudimavu', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Kambipura', 'kambipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Kanaminake', 'kanaminake', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Kumbalagodu', 'kumbalagodu', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Kumbalgodu', 'kumbalgodu', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Tagachiguppe', 'tagachiguppe', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 36, 'PD-36', 'Kumbalgodu Special Development Zone', false, 'Venkatapura', 'venkatapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Chikkeluru', 'chikkeluru', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Chikkeluru Rampura', 'chikkelururampura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Chikkeluru Venkatapura', 'chikkeluruvenkatapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Dodda Alada Mara', 'doddaaladamara', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Kethohalli', 'kethohalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Kethohalli Narasipura', 'kethohallinarasipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Kethohalli Rampura', 'kethohallirampura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Koluru', 'koluru', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Koluru Gurarayanapura', 'kolurugurarayanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Koluru Nanjundapura', 'kolurunanjundapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 37, 'PD-37', 'Dodda Alada Mara', false, 'Sheshagiripura', 'sheshagiripura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Bheemanakuppe', 'bheemanakuppe', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Bhimanakuppe', 'bhimanakuppe', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Bhimanakuppe Ramasagar', 'bhimanakupperamasagar', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Kenchanapura', 'kenchanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Kommagatta', 'kommagatta', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Kommagattakrishnapura', 'kommagattakrishnapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Maligondanahalli', 'maligondanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Maragondanahalli', 'maragondanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Maragondanahalli Krishnasagar', 'maragondanahallikrishnasagar', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Ramasandra', 'ramasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Ramohalli', 'ramohalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 38, 'PD-38', 'Sulikeri - Bheemanakuppe', false, 'Sulikeri', 'sulikeri', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Channenahalli', 'channenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Kannelli', 'kannelli', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Kodagihalli', 'kodagihalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Manganahalli', 'manganahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Sheegehalli', 'sheegehalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Yalachaguppe', 'yalachaguppe', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Yalachaguppe Rampura', 'yalachagupperampura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 39, 'PD-39', 'Sheegehalli - Yelachaguppe', false, 'Yelachaguppe', 'yelachaguppe', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Adakimaranahalli', 'adakimaranahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Byandahalli', 'byandahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Bylakonenahalli', 'bylakonenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Dasanapura', 'dasanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Dombarahalli', 'dombarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Gangondanahalli', 'gangondanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Gavipalya', 'gavipalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Harokyathanahalli', 'harokyathanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Kachohalli', 'kachohalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Kadaranahalli', 'kadaranahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Lakkenahalli', 'lakkenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Lakshmipura', 'lakshmipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Machohalli', 'machohalli', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Madavara', 'madavara', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Makali', 'makali', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Narayanapalya', 'narayanapalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Siddanahosahalli', 'siddanahosahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Srikantapura', 'srikantapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 40, 'PD-40', 'Makali - Machohalli', false, 'Vaddarahalli', 'vaddarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Aluru', 'aluru', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Bilijaji', 'bilijaji', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Hanumanthasagara', 'hanumanthasagara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Heggadadevanapura', 'heggadadevanapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Hesaraghatta', 'hesaraghatta', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Hurlichikkanahalli', 'hurlichikkanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Kodagi Tirumalapura', 'kodagitirumalapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Kuduragere', 'kuduragere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Muniyanapalya', 'muniyanapalya', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Narasipura', 'narasipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Sasiveghatta', 'sasiveghatta', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Tarabanahalli', 'tarabanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Thammarasanahalli', 'thammarasanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Thammenahalli', 'thammenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 41, 'PD-41', 'Aluru', false, 'Thorenagasandra', 'thorenagasandra', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Addiganhalli', 'addiganhalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Avalahalli', 'avalahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Honnenahalli', 'honnenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Itagalpura', 'itagalpura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Ivarakandapura', 'ivarakandapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Jarakabandekaval (T4)', 'jarakabandekavalt4', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Kalenahalli', 'kalenahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Kondashettyhalli', 'kondashettyhalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Krishnarajapura', 'krishnarajapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Krishnasagara', 'krishnasagara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Linganahalli', 'linganahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Lingarajapura', 'lingarajapura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Lingarajasagara', 'lingarajasagara', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Madagirihalli', 'madagirihalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Madappanahalli', 'madappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Mavallipura', 'mavallipura', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Muttakarahalli', 'muttakarahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Mylappanahalli', 'mylappanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Rajakunte', 'rajakunte', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Rajanakunte', 'rajanakunte', 'pd_label', 'high', 'RMP 2031 Vol-4 PDR — PD name'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Ramagondanahalli', 'ramagondanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Sheekoti', 'sheekoti', 'locality', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Shinganayakanahalli', 'shinganayakanahalli', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)'),
  ('Bengaluru', 42, 'PD-42', 'Rajanakunte', false, 'Shinganayakanahalli Amanikere', 'shinganayakanahalliamanikere', 'village', 'high', 'RMP 2031 Index Map (BDA, Nov 2017)')
ON CONFLICT (city, locality_norm, pd_number) DO NOTHING;
