-- 20260507_q1_2026_v0_2_data_refresh.sql
-- =============================================================================
-- REDIP Bengaluru Micro-Market Rate Pack v0.2 — Q1 2026 refresh
-- Generated: 2026-05-07T14:04:43.868Z
-- Source: redip_bengaluru_micro_market_rates_v0_2_2026Q1.json (172 records)
-- =============================================================================
--
-- Replaces existing Q1 2026 IPC rows in office / retail / industrial /
-- hospitality / micro-market benchmark tables with the v0.2 dataset, which
-- is more granular (per-submarket office rents + vacancy, per-corridor retail
-- rent, per-segment industrial rent + land value, micro-market-level
-- residential listings).
--
-- DELETE policy: scoped to city='Bengaluru' AND data_type/level matching the
-- v0.2 cohort (IPC Q1 2026 + listing Q1 2026). Pre-existing non-Q1-2026 rows
-- (e.g. internal Apr 2026 verified comps) are preserved.
--
-- New asset classes the existing schema can't hold (Builder floor, Plotted
-- development, Villa/independent house, Land - residential plotted, Guidance
-- value) are recorded in TODO_DATA.md for follow-up schema work, NOT
-- silently dropped.

BEGIN;


-- ── Office: 9 submarkets (each with vacancy + stock-weighted rent) ──
DELETE FROM office_market_benchmarks WHERE city='Bengaluru';

INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'CBD/Off-CBD', 'CBD / Central', 'submarket', 2, 162, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Bengaluru total', 'Citywide', 'ipc_zone', 7.8, 97, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Suburban East', 'East / Inner East', 'submarket', 3.2, 137, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Peripheral East', 'East / Whitefield', 'submarket', 9.4, 73.5, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Peripheral North', 'North / Airport corridor', 'submarket', 19.3, 74.6, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Suburban North West', 'North-West / Established city', 'submarket', 40.7, 125, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Outer Ring Road', 'ORR / Tech belt', 'submarket', 4.5, 106, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Peripheral South', 'South / Hosur-E-City-Mysore Road', 'submarket', 9.5, 68.6, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');
INSERT INTO office_market_benchmarks (organization_id, city, submarket, cluster, level_type, vacancy_pct, stock_weighted_rent_psf_month, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Suburban South', 'South / Inner South', 'submarket', 14, 91, 'C&W Office Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-office-q1-2026.pdf?rev=1dc4caf4be5f4ad7aa866d9631ab0ffb', '2026-05-04', TRUE, 'IPC Grade-A Q1 2026 v0.2 — Vacancy context for rent underwriting and absorption assumptions.');

-- ── Retail: 12 high-street corridors ──
DELETE FROM retail_market_benchmarks WHERE city='Bengaluru' AND format='high_street';

INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Commercial Street', 'CBD / Shivajinagar retail', 'high_street', 416, 416, 416, 1, 4, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Vittal Mallya Road', 'CBD luxury retail', 'high_street', 413, 413, 413, 1, 2, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Brigade Road', 'CBD retail', 'high_street', 417, 417, 417, 1, 2, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'MG Road', 'CBD retail', 'high_street', 263, 263, 263, 1.1, 4, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Marathahalli Junction', 'East / ORR retail', 'high_street', 162, 162, 162, 1.3, 3, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Indiranagar 100 Feet Road', 'East premium retail', 'high_street', 353, 353, 353, 1.2, 6, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Kamanahalli Main Road', 'North-East retail', 'high_street', 298, 298, 298, 1.5, 5, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'New BEL Road', 'North-West retail', 'high_street', 167, 167, 167, 1.2, 3, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Sampige Road, Malleshwaram', 'North-West retail', 'high_street', 157, 157, 157, 1.9, 3, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Jayanagar 4th Block, 11th Main', 'South premium retail', 'high_street', 232, 232, 232, 1.5, 5, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Koramangala 80 Feet Road', 'South premium retail', 'high_street', 220, 220, 220, 2, 7, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');
INSERT INTO retail_market_benchmarks (organization_id, city, corridor, cluster, format, rent_low_psf_month, rent_high_psf_month, rent_avg_psf_month, qoq_change_pct, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'HSR Layout 27th Main', 'South-East retail', 'high_street', 257, 257, 257, 1.7, 5, 'C&W Retail Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india-bengaluru-retail-q1-2026.pdf?rev=283dea49f8954d569f15eed639cb769e', '2026-05-04', TRUE, 'IPC Q1 2026 v0.2 — Ground-floor vanilla store asking rent on carpet area. Use only for high-street retail, not mall/upper-floor/neighbourhood-shop rent.');

-- ── Industrial / Warehouse / Land: 10 submarkets ──
DELETE FROM industrial_market_benchmarks WHERE city='Bengaluru';

INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Narsapura', 'East industrial', 'industrial', 23, 27, 25, 30, 3, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted industrial rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Doddaballapur', 'North industrial', 'industrial', 21, 25, 25, 35, 3, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted industrial rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Peenya', 'North-West industrial', 'industrial', 42, 45, 220, 260, 3, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted industrial rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Bommasandra', 'South industrial', 'industrial', 30, 33, 175, 195, 3, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted industrial rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Kumbalgodu', 'West industrial', 'industrial', 23, 25, 110, 130, 2, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted industrial rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Hoskote / Malur', 'East warehouse', 'warehouse', 23, 26, 35, 40, 4, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted warehouse rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Devanahalli / KIADB Hitech Zone', 'North industrial/warehouse', 'warehouse', 30, 35, 60, 100, 4, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted warehouse rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Hosur Road / Jigani / Attibele', 'South industrial/warehouse', 'warehouse', 24, 27, 70, 120, 3, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted warehouse rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Bidadi', 'West industrial/warehouse', 'warehouse', 25, 30, 55, 65, 3, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted warehouse rents by submarket.');
INSERT INTO industrial_market_benchmarks (organization_id, city, submarket, cluster, segment, rent_low_psf_month, rent_high_psf_month, land_value_low_inr_mn_per_acre, land_value_high_inr_mn_per_acre, yoy_change_pct, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Nelamangala', 'West warehouse', 'warehouse', 22, 25, 35, 50, 4, 'C&W Industrial H2 2025', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2025/q4/apac-and-gc/india---bengaluru---industrial-h2-2025_final.pdf?rev=ebea5be198bf4d4f97c9ba9c00eacafc', '2026-05-04', TRUE, 'IPC H2 2025 v0.2 — Quoted warehouse rents by submarket.');

-- ── Hospitality: 2 clusters ──
DELETE FROM hospitality_market_benchmarks WHERE city='Bengaluru';

INSERT INTO hospitality_market_benchmarks (organization_id, city, submarket, cluster, segment, adr_low_inr, adr_high_inr, occupancy_pct, revpar_inr, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Bengaluru citywide', 'Citywide', 'citywide', 9600, 9600, 67, 6400, 'Horwath HTL India Hotel Market Review 2025', 'https://horwathhtl.com/wp-content/uploads/2026/02/HHTL-India-Market-Report-2025.pdf', '2026-05-04', TRUE, 'Horwath HTL 2025 v0.2 — Citywide RevPAR, not micro-market ADR. Segment by luxury/upscale/economy before underwriting.');
INSERT INTO hospitality_market_benchmarks (organization_id, city, submarket, cluster, segment, adr_low_inr, adr_high_inr, occupancy_pct, revpar_inr, source, source_url, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'North Bengaluru / Airport hospitality', 'North / Airport corridor', 'upper_upscale', 12500, 12500, 66.5, NULL, 'Horwath HTL India Hotel Market Review 2025', 'https://horwathhtl.com/wp-content/uploads/2026/02/HHTL-India-Market-Report-2025.pdf', '2026-05-04', TRUE, 'Horwath HTL 2025 v0.2 — Use for Devanahalli/KIA/Aerotropolis hospitality underwriting; not comparable to CBD business hotels.');

-- ── Micro-market: 27 listing-portal + 14 IPC zone rows ──
DELETE FROM micro_market_benchmarks WHERE city='Bengaluru' AND data_type IN ('listing_q1_2026','ipc_q1_2026','listing_q1_2026_v0_2','ipc_q1_2026_v0_2');

INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'AECS Layout Marathahalli', 9622, 15416, NULL, NULL, 44, 'East / Marathahalli-Whitefield connector', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — The 44% q-o-q flag looks abnormal; treat as listing-mix movement, not real market appreciation.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Marathahalli', 7033, 11451, NULL, NULL, 2, 'East / ORR-Whitefield connector', 'Q1 2026 v0.2', 'MagicBricks Marathahalli', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Marathahalli-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Older resale-heavy market; should not be blended with Grade-A ORR gated projects.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Whitefield', 9960, 16451, NULL, NULL, 2, 'East / Peripheral East', 'Q1 2026 v0.2', 'MagicBricks Whitefield', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Whitefield-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Established IT residential market; apartment benchmark should be cross-checked against project age: ITPL/EPIP premium vs Kadugodi/Varthur fringe.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Electronic City', 6419, 11338, NULL, NULL, 6, 'Far South / Peripheral South', 'Q1 2026 v0.2', 'MagicBricks Electronic City', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Electronic-City-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Large spread between Phase I, Phase II, Neeladri Road and Hosur Road frontage; use sub-cluster tagging.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Yelahanka', 7489, 12505, NULL, NULL, 2, 'North / Airport corridor', 'Q1 2026 v0.2', 'MagicBricks Yelahanka', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Yelahanka-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Wide plot market; keep old Yelahanka, New Town and Bellary Road as separate segments.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Yelahanka New Town', 7131, 11763, NULL, NULL, 7, 'North / Airport corridor', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — More planned/residential than Devanahalli; plot benchmark is relevant but verify against BDA vs private layout status.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Devanahalli', 7772, 11365, NULL, NULL, 4, 'North / Airport-Aerospace corridor', 'Q1 2026 v0.2', 'MagicBricks Devanahalli', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Devanahalli-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Airport/aerospace driven; land and plotted data need more validation than apartment values because inventory is township-heavy and scattered.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Hebbal', 12270, 20404, NULL, NULL, 2, 'North / Airport-Manyata corridor', 'Q1 2026 v0.2', 'MagicBricks Hebbal', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Hebbal-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Premium north Bengaluru node driven by ORR, airport access and Manyata proximity; do not blend with Yelahanka/Thanisandra.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Hebbal Kempapura', 6896, 11883, NULL, NULL, 2, 'North / Hebbal fringe', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Useful lower-premium comparator to Hebbal proper.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Thanisandra', 8989, 14288, NULL, NULL, 2, 'North / Manyata-Hebbal fringe', 'Q1 2026 v0.2', 'MagicBricks Thanisandra', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Thanisandra-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Manyata spillover market; split Thanisandra Main Road, Rachenahalli, Nagavara, RK Hegde Nagar for real comping.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Hennur Bagalur Main Road', 7394, 12173, NULL, NULL, 1, 'North-East / Hennur-Bagalur belt', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Fringe of Hennur-Bagalur growth corridor; stronger plotted/township relevance than CBD-style apartment comparability.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Hennur Main Road', 7482, 13040, NULL, NULL, 0.4, 'North-East / Hennur-Bagalur belt', 'Q1 2026 v0.2', 'MagicBricks Hennur Main Road', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Hennur-Main-Road-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Residential family market with premium around Hennur-Bagalur/Kothanur and discount toward interior villages.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Rajajinagar', 18251, 29153, NULL, NULL, 3, 'North-West / Established city', 'Q1 2026 v0.2', 'MagicBricks Rajajinagar', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Rajajinagar-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — High-value established west/north-west market; Orion/Metro/old layout redevelopment premium.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Rajajinagar 1st Block', 21148, 29252, NULL, NULL, 6, 'North-West / Established city', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Sub-pocket with stronger premium than generic Rajajinagar benchmark.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Defence Colony Indiranagar', 21626, 24941, NULL, NULL, -0.2, 'Off-Central / East premium', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Ultra-premium Indiranagar sub-pocket; use for redevelopment/builder-floor comparables only, not generic East Bengaluru.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Indiranagar', 14740, 22807, NULL, NULL, -0.3, 'Off-Central / East premium', 'Q1 2026 v0.2', 'MagicBricks Indiranagar', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Indiranagar-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Premium old-Bengaluru land market; plot/house value more relevant than flat average for redevelopment.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Bellandur', 11121, 19092, NULL, NULL, 1, 'Outer Ring Road / South-East tech belt', 'Q1 2026 v0.2', 'MagicBricks Bellandur', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Bellandur-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Premium ORR rental/resale node; lake/infrastructure issues create project-level dispersion.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Marathahalli-Sarjapur ORR', 11507, 18783, NULL, NULL, 4, 'Outer Ring Road / South-East tech belt', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Use as the apartment price anchor for ORR tech belt near Kadubeesanahalli, Bellandur, Embassy TechVillage access.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Bannerghatta Main Road', 7237, 12810, NULL, NULL, 1, 'South / IIM-Arekere-Begur belt', 'Q1 2026 v0.2', 'MagicBricks Bannerghatta Main Road', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Bannerghatta-Main-Road-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Highly uneven by sub-cluster: Arekere/IIM frontage vs Gottigere/Begur/Anekal side.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Jayanagar', 11114, 17467, NULL, NULL, 3, 'South / Inner premium', 'Q1 2026 v0.2', 'MagicBricks Jayanagar', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Jayanagar-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Premium south Bengaluru old-layout market; land-rich house values are key for redevelopment feasibility.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Koramangala', 11827, 19347, NULL, NULL, 1, 'South / Inner premium', 'Q1 2026 v0.2', 'MagicBricks Koramangala', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Koramangala-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Prime lifestyle/startup/cafe district; strongly project-vintage sensitive.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Koramangala 1st Block', 14483, 23555, NULL, NULL, NULL, 'South / Inner premium', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Higher-income sub-cluster within Koramangala; useful for premium builder-floor/villa redevelopment assumptions.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'JP Nagar', 7426, 12361, NULL, NULL, 2, 'South / Inner-to-mid segment', 'Q1 2026 v0.2', 'MagicBricks JP Nagar', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-JP-Nagar-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Stage-wise dispersion is huge; split Phase 1-2 vs Phase 7-9 if used for actual underwriting.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Kanakapura Road', 7788, 13200, NULL, NULL, 2, 'South / Metro Green Line-NICE corridor', 'Q1 2026 v0.2', 'MagicBricks Kanakapura Road', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Kanakapura-Road-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Metro/NICE-driven south corridor; plotted-villa communities can trade materially above apartment benchmark.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'HSR Layout', 7714, 11012, NULL, NULL, -0.2, 'South-East / ORR-Sarjapur belt', 'Q1 2026 v0.2', 'MagicBricks HSR Layout', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-HSR-Layout-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Layout plots and independent houses are the real premium; apartment benchmark understates land-rich residential value.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Sarjapur Road', 8972, 15014, NULL, NULL, 1, 'South-East / ORR-Sarjapur belt', 'Q1 2026 v0.2', 'MagicBricks Sarjapur Road', 'https://www.magicbricks.com/Property-Rates-Trends/Multistorey-Apartment-rates-Sarjapur-Road-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Fast-growth corridor; split into inner Sarjapur Road/ORR-adjacent, Carmelaram, Dommasandra/Sarjapura fringe for REDIP.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Ambalipura-Sarjapur Road', 9031, 14740, NULL, NULL, 1, 'South-East / Sarjapur-ORR belt', 'Q1 2026 v0.2', 'MagicBricks Property Rates', 'https://www.magicbricks.com/Property-Rates-Trends/ALL-RESIDENTIAL-rates-in-Bangalore', 'listing_q1_2026_v0_2', '2026-05-04', TRUE, 'Listing portal asking-price benchmark — Inner Sarjapur/ORR-adjacent node; more comparable to Bellandur/HSR than outer Sarjapura town.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Central', 18000, 30000, 0, 0, 0, 'CBD / Central', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (High-end residential) — Key submarkets: Lavelle Road, Palace Cross Road, Off Cunningham Road, Ulsoor Road, Richmond Road, Sankey Road. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'East', 9500, 14000, 7, 7, 1, 'East / Peripheral East', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (High-end residential) — Key submarkets: Whitefield, Old Airport Road. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'North', 9000, 13500, 7, 7, 1, 'North / Airport corridor', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (High-end residential) — Key submarkets: Hebbal, Jakkur, Devanahalli. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'South', 10550, 15000, 6, 6, 0, 'South / Inner premium', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (High-end residential) — Key submarkets: Koramangala, Bannerghatta Road, JP Nagar, Banashankari. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Central', 9500, 15000, 5, 5, 0, 'CBD / Central', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Brunton Road, Artillery Road, Ali Askar Road, Cunningham Road. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'East', 7500, 9500, 6, 6, 2, 'East / Peripheral East', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Whitefield, Old Airport Road, Old Madras Road, Budigere Cross. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Far South', 6500, 7500, 3, 3, 0, 'Far South / Electronic City-Attibele', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Electronic City, Attibele, Chandapura. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'North', 7500, 9000, 6, 6, 2, 'North / Airport corridor', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Hebbal, Bellary Road, Yelahanka, Doddaballapur Road, Hennur Road, Thanisandra Road. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'North-West', 7300, 8800, 4, 4, 1, 'North-West / Established city', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Malleshwaram, Rajajinagar, Tumkur Road. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Off-Central I', 10000, 14000, 2, 2, 0, 'Off-Central / East premium', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Vasanth Nagar, Richmond Town, Indiranagar. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'Off-Central II', 9000, 12000, 2, 2, 0, 'Off-Central / North-East old city', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Cox Town, Frazer Town, Benson Town. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'South', 7000, 9000, 3, 3, 0, 'South / Inner-to-peripheral', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Jayanagar, JP Nagar, Kanakapura Road, Bannerghatta Road, BTM Layout, Banashankari. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'South-East', 7800, 9000, 5, 5, 1, 'South-East / ORR-Sarjapur', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Sarjapur Road, Marathahalli-Sarjapur ORR, HSR Layout, Hosur Road. Use as calibration layer over listing portal micro-market values.');
INSERT INTO micro_market_benchmarks (organization_id, city, micro_market, avg_price_min_per_sqft, avg_price_max_per_sqft, yoy_growth_min_pct, yoy_growth_max_pct, qoq_change_pct, anchor_hub, data_period, source, source_url, data_type, as_of_date, is_verified, notes) VALUES ('d1218877-4d3a-4fe4-8d63-914fa8ffa94b', 'Bengaluru', 'West', 7000, 8000, 3, 3, 0, 'West / Mysore Road-Magadi', 'Q1 2026 v0.2', 'C&W Residential Q1 2026', 'https://assets.cushmanwakefield.com/-/media/cw/marketbeat-pdfs/2026/q1/apac-and-gc/india--bengaluru--residential-q1-2026_final.pdf?rev=b1899517f8b149418916aaf9d43b26d4', 'ipc_q1_2026_v0_2', '2026-05-04', TRUE, 'IPC submarket benchmark (Mid-segment residential) — Key submarkets: Mysore Road, Uttarahalli Main Road, Magadi Road. Use as calibration layer over listing portal micro-market values.');

-- ── Tier-2 follow-up (logged in TODO_DATA.md, not inserted in this migration) ──
-- The v0.2 dataset includes asset classes that don't fit the current
-- schema. Adding tables for them is a separate PR:
--   Builder floor apartments: 7
--   Plotted development / residential plot: 18
--   Land - residential plotted: 18
--   Residential house / villa: 13
--   Guidance value / circle rate: 11

COMMIT;

