#!/usr/bin/env python3
"""Phase 2a — partial zone enrichment via heuristics on the pypdf text.

The pypdf extractor reorders zone footers within a page, so the rich
in-line "ZONE X / GUIDANCE VALUE BANDWIDTH Rs.XXX to Rs.YYY" headers end
up grouped at the bottom of the per-page text instead of inline with the
streets they govern. Because of that we cannot ALWAYS associate each
street with its correct zone from text alone — but we can in the
common case where a page only contains a single zone.

This script:
  1. For each page, parse out every "ZONE X" + bandwidth pair.
  2. If a page has exactly one zone, every street on that page belongs
     to it — emit an UPDATE row for each.
  3. If a page has multiple zones, defer to Phase 2b (LLM multimodal),
     leave zone_code NULL.
  4. Write the SQL UPDATE batch to tmp/bbmp-street-zone-heuristic.sql
     for the operator (or the Node seed script) to apply.

Output: tmp/bbmp-street-zone-heuristic.sql plus a summary print.
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

TMP = Path(__file__).resolve().parent.parent / "tmp"
PAGES_DIR = TMP / "guidance-value"
INDEX_FILE = TMP / "bbmp-street-index.json"
OUT_SQL = TMP / "bbmp-street-zone-heuristic.sql"

# Matches "ZONE A" / "ZONE-A" / "Zone : A" / "ZONE  A " case-insensitive.
ZONE_RE = re.compile(r"^\s*ZONE\s*[-: ]?\s*([A-F])\b", re.IGNORECASE)
# Matches "GUIDANCE VALUE BANDWIDTH ... Rs. XXX to Rs. YYY" or "Rs. XXX & Above".
BAND_RE = re.compile(
    r"GUIDANCE\s+VALUE\s+BANDWIDTH[^\d]+(?:Rs\.?\s*)?([\d,]+)(?:[^\d]+?(?:Rs\.?\s*)?([\d,]+))?",
    re.IGNORECASE,
)


def parse_zone_footers(text: str) -> list[dict]:
    """Return [{zone_code, min, max}] for every zone declared on this page."""
    zones: list[dict] = []
    pending_zone = None
    for raw in text.splitlines():
        line = raw.strip()
        zone_match = ZONE_RE.match(line)
        if zone_match:
            if pending_zone:
                zones.append(pending_zone)
            pending_zone = {"zone_code": zone_match.group(1).upper(), "min": None, "max": None}
            continue
        if pending_zone:
            band_match = BAND_RE.search(line)
            if band_match:
                lo = int(band_match.group(1).replace(",", ""))
                hi = band_match.group(2)
                pending_zone["min"] = lo
                pending_zone["max"] = int(hi.replace(",", "")) if hi else None
                zones.append(pending_zone)
                pending_zone = None
    if pending_zone:
        zones.append(pending_zone)
    return zones


def main() -> int:
    if not PAGES_DIR.exists() or not INDEX_FILE.exists():
        print("ERROR: run extract-guidance-value-pdf.py and build-bbmp-street-index.py first", file=sys.stderr)
        return 1

    street_rows = json.loads(INDEX_FILE.read_text(encoding="utf-8"))
    streets_by_page: dict[int, list[dict]] = {}
    for r in street_rows:
        streets_by_page.setdefault(r["page_number"], []).append(r)

    sql_statements: list[str] = []
    pages_single_zone = 0
    pages_multi_zone = 0
    pages_no_zone = 0
    rows_to_update = 0

    for page_number in sorted(streets_by_page.keys()):
        page_file = PAGES_DIR / f"page-{page_number:03d}.txt"
        if not page_file.exists():
            continue
        text = page_file.read_text(encoding="utf-8", errors="replace")
        zones = parse_zone_footers(text)

        if not zones:
            pages_no_zone += 1
            continue
        if len(zones) > 1:
            pages_multi_zone += 1
            continue

        # Single-zone page — assign that zone to every street on the page.
        pages_single_zone += 1
        z = zones[0]
        for r in streets_by_page[page_number]:
            street_q = r["street_name_en"].replace("'", "''")
            ward = r.get("ward_no")
            ward_clause = f"ward_no = {int(ward)}" if ward is not None else "ward_no IS NULL"
            min_v = "NULL" if z["min"] is None else str(z["min"])
            max_v = "NULL" if z["max"] is None else str(z["max"])
            sql_statements.append(
                f"UPDATE regulatory_data.bbmp_street_index SET "
                f"zone_code = '{z['zone_code']}', "
                f"guidance_value_band_min_inr = {min_v}, "
                f"guidance_value_band_max_inr = {max_v}, "
                f"confidence_score = 0.75 "
                f"WHERE page_number = {page_number} AND lower(street_name_en) = lower('{street_q}') "
                f"AND {ward_clause} AND zone_code IS NULL;"
            )
            rows_to_update += 1

    TMP.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text(
        "-- Phase 2a heuristic zone enrichment generated by\n"
        "-- scripts/heuristic-enrich-bbmp-zones.py.\n"
        "-- Apply via: node scripts/apply-bbmp-zone-heuristic.js (uses backend pg pool).\n\n"
        "BEGIN;\n"
        + "\n".join(sql_statements)
        + "\nCOMMIT;\n",
        encoding="utf-8",
    )

    print(f"Single-zone pages    : {pages_single_zone}  ({rows_to_update} street rows to update)")
    print(f"Multi-zone pages     : {pages_multi_zone}  (deferred to Phase 2b LLM enrichment)")
    print(f"Pages w/ no zone in text-extract: {pages_no_zone}")
    print(f"Wrote {len(sql_statements)} UPDATE statements to {OUT_SQL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
